language: node_js
install:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" = "linux" || "$TRAVIS_OS_NAME" = "osx" ]]; then npm install git+https://github.com/RyanAfrish7/node-loudness.git; fi
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then npm install win-audio@^1.2.0; fi
node_js:
  - 8
sudo: required
os:
  - linux
  - osx
  - windows
